### ISSUE TITLE
Could not find the file

### ISSUE THREAD

**Issue by ronantaylorware** [lansalot/AOGConfigOMatic#6]
FYI

First time running program, extracted to desktop. Ran the exe, teensy tab, when pressing refresh list an unhandled exception pops up could not find the file firmwares.csv. Mustn't be downloading, not sure if windows firewall blocking or something.

Messagebox says Error downloading C:\Users\.......\Firmwares.csv

Tried adding the exe to windows firewall and allowing everything same result.

Cheers

**Comment by ronantaylorware** [comment]
Found the firmwares.csv on here, put in folder manually, works a treat. 
Program downloaded the hex it needed no problem, teensy and f9p all flashed, love it!

**Comment by lansalot** [comment]
Fixed in #7, sorry about that, missed it during testing. Fixed also flushed a bug in that it wouldn't even load local hex if no CSV present. Please try and confirm?

**Comment by karoolis** [comment]
Am I blind or there is no AOGConfigOMatic.exe file??? :(((

**Comment by lansalot** [comment]
> Am I blind or there is no AOGConfigOMatic.exe file??? :(((

Look in Releases

**Comment by lansalot** [comment]
Welp, didn't hear back, so presume all good now.
